export interface ChallengeMaze {
  description: string;
  gridSize: number;
  start: [number, number];
  goal: [number, number];
  walls: [number, number][];
}

export interface Level {
  id: number;
  name: string;
  description: string;
  gridSize: number;
  start: [number, number];
  goal: [number, number];
  walls: [number, number][];
  hint: string;
  challenge: ChallengeMaze;
}

export const levels: Level[] = [
  // Level 1: Langkah dasar - move_right()
  {
    id: 1,
    name: "First Step",
    description: "Gerakkan karakter ke kanan untuk mencapai tujuan!",
    gridSize: 5,
    start: [0, 0],
    goal: [0, 4],
    walls: [
      [1, 0],
      [1, 1],
      [1, 2],
      [1, 3],
      [3, 1],
      [3, 2],
      [3, 3],
      [3, 4],
    ],
    hint: "# Level 1: Langkah Pertama\n# Gunakan move_right() untuk gerakkan karakter ke kanan\n# Setiap perintah = 1 langkah\n\nmove_right()  # Langkah ke-1: gerak kanan\nmove_right()  # Langkah ke-2: gerak kanan\nmove_right()  # Langkah ke-3: gerak kanan\nmove_right()  # Langkah ke-4: sampai tujuan!\n",
    challenge: {
      description: "Sekarang coba sendiri! Gerakkan karakter ke bawah untuk mencapai tujuan.",
      gridSize: 5,
      start: [0, 0],
      goal: [3, 0],
      walls: [
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [2, 1],
        [2, 2],
        [2, 3],
        [2, 4],
        [3, 1],
        [3, 2],
        [3, 3],
        [3, 4],
      ],
    },
  },

  // Level 2: Gabungkan arah - move_right() + move_down()
  {
    id: 2,
    name: "Turn!",
    description: "Gabungkan gerakan ke kanan dan ke bawah untuk melewati jalur berbentuk L.",
    gridSize: 5,
    start: [0, 0],
    goal: [4, 4],
    walls: [
      [0, 3],
      [0, 4],
      [1, 0],
      [1, 3],
      [1, 4],
      [2, 3],
      [2, 4],
      [3, 0],
      [3, 1],
      [4, 0],
      [4, 1],
    ],
    hint: "# Level 2: Belok!\n# Gabungkan move_right() dan move_down()\n# Jalur berbentuk L: kanan dulu, lalu belok ke bawah\n\nmove_right()   # Gerak kanan\nmove_right()   # Gerak kanan\nmove_down()    # Belok! Gerak bawah\nmove_down()    # Gerak bawah\nmove_down()    # Gerak bawah\nmove_right()   # Belok lagi! Gerak kanan\nmove_right()   # Gerak kanan\nmove_down()    # Langkah terakhir ke bawah\n",
    challenge: {
      description: "Sekarang coba sendiri! Gabungkan move_down() dan move_right() untuk jalur L terbalik.",
      gridSize: 5,
      start: [0, 0],
      goal: [4, 3],
      walls: [
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [2, 1],
        [2, 2],
        [2, 3],
        [2, 4],
        [3, 4],
        [4, 4],
      ],
    },
  },

  // Level 3: Loop dasar - for range
  {
    id: 3,
    name: "Loop !",
    description: "Gunakan loop di Python untuk mengulang Gerakan!",
    gridSize: 7,
    start: [0, 0],
    goal: [6, 6],
    walls: [
      [1, 0],
      [1, 1],
      [1, 2],
      [1, 3],
      [1, 4],
      [1, 5],
      [2, 5],
      [3, 5],
      [4, 5],
      [5, 5],
    ],
    hint: "# Level 3: Loop Power!\n# 'for' loop mengulang perintah berkali-kali\n# range(6) artinya ulangi 6 kali (0,1,2,3,4,5)\n\n# Loop pertama: gerak kanan 6 langkah\nfor i in range(6):\n    move_right()  # Diulang 6 kali\n\n# Loop kedua: gerak bawah 6 langkah\nfor i in range(6):\n    move_down()   # Diulang 6 kali\n",
    challenge: {
      description: "Sekarang coba sendiri! Gunakan loop untuk gerak bawah dulu, lalu kanan.",
      gridSize: 6,
      start: [0, 0],
      goal: [5, 5],
      walls: [
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [0, 5],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [1, 5],
        [2, 1],
        [2, 2],
        [2, 3],
        [2, 4],
        [2, 5],
        [3, 1],
        [3, 2],
        [3, 3],
        [3, 4],
        [3, 5],
        [4, 1],
        [4, 2],
        [4, 3],
        [4, 4],
        [4, 5],
      ],
    },
  },

  // Level 4: Variabel - simpan jumlah langkah dalam variabel
  {
    id: 4,
    name: "Variabel",
    description: "Simpan jumlah langkah dalam variabel, lalu gunakan di loop!",
    gridSize: 6,
    start: [0, 0],
    goal: [5, 5],
    walls: [
      [1, 0],
      [1, 1],
      [1, 2],
      [1, 3],
      [1, 4],
      [3, 0],
      [3, 1],
      [3, 2],
      [3, 3],
      [3, 4],
    ],
    hint: "# Level 4: Kekuatan Variabel\n# Variabel menyimpan nilai yang bisa dipakai ulang\n# Jika ingin mengubah jumlah langkah, cukup ubah variabelnya!\n\nlangkah = 5  # Simpan angka 5 ke variabel 'langkah'\n\n# Gunakan variabel di range()\nfor i in range(langkah):\n    move_right()  # Gerak kanan sebanyak 'langkah' kali\n\nfor i in range(langkah):\n    move_down()   # Gerak bawah sebanyak 'langkah' kali\n",
    challenge: {
      description: "Sekarang coba sendiri! Gunakan variabel untuk menyimpan jumlah langkah.",
      gridSize: 5,
      start: [0, 0],
      goal: [4, 4],
      walls: [
        [1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [3, 1],
        [3, 2],
        [3, 3],
        [3, 4],
      ],
    },
  },

  // Level 5: Fungsi & Pola - definisikan fungsi untuk pola berulang
  {
    id: 5,
    name: "Function",
    description: "Buat fungsi untuk pola gerakan yang berulang: kanan 2, bawah 2!",
    gridSize: 7,
    start: [0, 0],
    goal: [6, 6],
    walls: [
      [0, 3],
      [0, 4],
      [0, 5],
      [0, 6],
      [1, 0],
      [1, 4],
      [1, 5],
      [1, 6],
      [2, 0],
      [2, 1],
      [2, 5],
      [2, 6],
      [3, 0],
      [3, 1],
      [3, 2],
      [3, 3],
      [4, 0],
      [4, 1],
      [4, 2],
      [4, 3],
      [5, 0],
      [5, 1],
      [5, 2],
      [5, 3],
      [5, 4],
      [5, 5],
      [6, 0],
      [6, 1],
      [6, 2],
      [6, 3],
      [6, 4],
      [6, 5],
    ],
    hint: "# Level 5: Pola Berulang!\n# Fungsi adalah blok kode yang bisa dipanggil berkali-kali\n# 'def' untuk mendefinisikan fungsi\n\ndef langkah_tangga():       # Definisikan fungsi bernama 'langkah_tangga'\n    move_right()            # Gerak kanan\n    move_right()            # Gerak kanan lagi\n    move_down()             # Gerak bawah\n    move_down()             # Gerak bawah lagi\n\n# Panggil fungsi 3 kali menggunakan loop\n# Setiap panggilan = kanan 2 + bawah 2\nfor i in range(3):          # Ulangi 3 kali\n    langkah_tangga()        # Panggil fungsi yang sudah dibuat\n",
    challenge: {
      description: "Sekarang coba sendiri! Buat fungsi untuk pola berulang: bawah 2, kanan 2.",
      gridSize: 7,
      start: [0, 0],
      goal: [6, 6],
      walls: [
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [0, 5],
        [0, 6],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [1, 5],
        [1, 6],
        [2, 3],
        [2, 4],
        [2, 5],
        [2, 6],
        [3, 3],
        [3, 4],
        [3, 5],
        [3, 6],
        [4, 5],
        [4, 6],
        [5, 5],
        [5, 6],
      ],
    },
  },

  // Level 6: If-else & Sensor - gunakan can_move_*() untuk navigasi
  {
    id: 6,
    name: "If else",
    description: "Gunakan can_move_right() dan can_move_down() untuk menavigasi labirin!",
    gridSize: 6,
    start: [0, 0],
    goal: [5, 5],
    walls: [
      [0, 4],
      [0, 5],
      [1, 0],
      [1, 1],
      [1, 2],
      [1, 4],
      [1, 5],
      [2, 0],
      [2, 1],
      [2, 2],
      [3, 0],
      [3, 1],
      [3, 2],
      [3, 3],
      [3, 4],
      [4, 0],
      [4, 1],
      [4, 2],
      [4, 3],
      [4, 4],
      [5, 0],
      [5, 1],
      [5, 2],
      [5, 3],
      [5, 4],
    ],
    hint: "# Level 6: Sensor & Keputusan\n# can_move_right() mengecek apakah ada dinding di kanan\n# 'if' menjalankan kode jika kondisi benar (True)\n# 'elif' (else if) cek kondisi lain jika 'if' salah\n\nfor i in range(10):        # Ulangi 10 kali\n    if can_move_right():   # Jika bisa gerak kanan...\n        move_right()       # ...maka gerak kanan\n    elif can_move_down():  # Jika tidak, cek bisa gerak bawah?\n        move_down()        # ...maka gerak bawah\n",
    challenge: {
      description: "Sekarang coba sendiri! Gunakan sensor if/elif untuk navigasi labirin berbeda.",
      gridSize: 6,
      start: [0, 0],
      goal: [5, 5],
      walls: [
        [0, 2],
        [0, 3],
        [0, 4],
        [0, 5],
        [1, 2],
        [1, 3],
        [1, 4],
        [1, 5],
        [2, 0],
        [2, 4],
        [2, 5],
        [3, 0],
        [3, 1],
        [3, 2],
        [3, 5],
        [4, 0],
        [4, 1],
        [4, 2],
        [5, 0],
        [5, 1],
        [5, 2],
        [5, 3],
      ],
    },
  },

  // Level 7: While loop - gunakan while untuk navigasi dinamis
  {
    id: 7,
    name: "While Loop",
    description: "Gunakan while loop untuk bergerak sampai mencapai tujuan!",
    gridSize: 7,
    start: [0, 0],
    goal: [6, 6],
    walls: [
      [0, 2],
      [1, 2],
      [2, 2],
      [2, 4],
      [3, 4],
      [4, 4],
      [4, 0],
      [4, 1],
      [4, 2],
      [6, 2],
      [6, 3],
      [6, 4],
    ],
    hint: "# Level 7: While Loop\n# 'while' terus mengulang SELAMA kondisi bernilai True\n# get_row() = posisi baris, get_col() = posisi kolom\n# Loop berhenti saat sampai di baris 6, kolom 6\n\nwhile get_row() != 6 or get_col() != 6:  # Selama belum di tujuan\n    if can_move_right():    # Prioritas 1: coba kanan\n        move_right()\n    elif can_move_down():   # Prioritas 2: coba bawah\n        move_down()\n    elif can_move_left():   # Prioritas 3: coba kiri\n        move_left()\n    elif can_move_up():     # Prioritas 4: coba atas\n        move_up()\n",
    challenge: {
      description: "Sekarang coba sendiri! Gunakan while loop untuk navigasi labirin baru.",
      gridSize: 7,
      start: [0, 0],
      goal: [6, 6],
      walls: [
        [0, 3],
        [1, 1],
        [1, 3],
        [2, 1],
        [2, 5],
        [3, 3],
        [3, 5],
        [4, 1],
        [4, 3],
        [5, 1],
        [5, 5],
        [6, 3],
      ],
    },
  },

  // Level 8: Nested loop - pola zigzag
  {
    id: 8,
    name: "Nested loop!",
    description: "Gunakan nested loop untuk membuat pola zigzag: kanan-kanan-bawah, kiri-kiri-bawah.",
    gridSize: 5,
    start: [0, 0],
    goal: [4, 0],
    walls: [
      [0, 3],
      [0, 4],
      [1, 0],
      [1, 1],
      [1, 3],
      [1, 4],
      [2, 3],
      [2, 4],
      [3, 1],
      [3, 2],
      [3, 3],
      [3, 4],
      [4, 1],
      [4, 2],
      [4, 3],
      [4, 4],
    ],
    hint: "# Level 8: Zigzag!\n# Nested loop = loop di dalam loop\n# Loop luar mengulang pola zigzag 2 kali\n# Loop dalam mengontrol jumlah langkah per arah\n\nfor i in range(2):          # Ulangi pola zigzag 2 kali\n    for j in range(2):      # Gerak kanan 2 langkah\n        move_right()\n    for i in range(2):      # Gerak bawah 2 langkah\n        move_down()\n    for j in range(2):      # Gerak kiri 2 langkah (balik!)\n        move_left()\n    for i in range(2):      # Gerak bawah 2 langkah lagi\n        move_down()\n",
    challenge: {
      description: "Sekarang coba sendiri! Buat pola zigzag dengan nested loop di maze berbeda.",
      gridSize: 7,
      start: [0, 0],
      goal: [6, 0],
      walls: [
        [0, 4],
        [0, 5],
        [0, 6],
        [1, 0],
        [1, 1],
        [1, 4],
        [1, 5],
        [1, 6],
        [2, 4],
        [2, 5],
        [2, 6],
        [3, 1],
        [3, 2],
        [3, 3],
        [3, 4],
        [3, 5],
        [3, 6],
        [4, 4],
        [4, 5],
        [4, 6],
        [5, 0],
        [5, 1],
        [5, 4],
        [5, 5],
        [5, 6],
        [6, 3],
        [6, 4],
        [6, 5],
        [6, 6],
      ],
    },
  },

  // Level 9: Fungsi dengan parameter
  {
    id: 9,
    name: "Function Parameter",
    description: "Buat fungsi dengan parameter untuk mengontrol jumlah langkah!",
    gridSize: 8,
    start: [0, 0],
    goal: [7, 7],
    walls: [
      [1, 0],
      [1, 1],
      [1, 2],
      [1, 3],
      [1, 4],
      [1, 5],
      [1, 6],
      [3, 1],
      [3, 2],
      [3, 3],
      [3, 4],
      [3, 5],
      [3, 6],
      [3, 7],
      [5, 0],
      [5, 1],
      [5, 2],
      [5, 3],
      [5, 4],
      [5, 5],
      [5, 6],
    ],
    hint: "# Level 9: Fungsi Pintar\n# Fungsi bisa menerima parameter (nilai input)\n# 'n' adalah parameter yang menentukan jumlah langkah\n\ndef gerak_kanan(n):         # Fungsi: gerak kanan sebanyak n kali\n    for i in range(n):\n        move_right()\n\ndef gerak_kiri(n):          # Fungsi: gerak kiri sebanyak n kali\n    for i in range(n):\n        move_left()\n\n# Pola zig-zag: kanan 7, turun 2, kiri 7, turun 2, kanan 7, turun 3\ngerak_kanan(7)              # Gerak kanan 7 langkah\nmove_down()                 # Turun\nmove_down()                 # Turun\ngerak_kiri(7)               # Balik kiri 7 langkah\nmove_down()                 # Turun\nmove_down()                 # Turun\ngerak_kanan(7)              # Kanan lagi 7 langkah\nmove_down()                 # Turun\nmove_down()                 # Turun\nmove_down()                 # Sampai tujuan!\n",
    challenge: {
      description: "Sekarang coba sendiri! Buat fungsi dengan parameter untuk navigasi maze baru.",
      gridSize: 7,
      start: [0, 0],
      goal: [6, 6],
      walls: [
        [1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [1, 5],
        [3, 1],
        [3, 2],
        [3, 3],
        [3, 4],
        [3, 5],
        [3, 6],
        [5, 0],
        [5, 1],
        [5, 2],
        [5, 3],
        [5, 4],
        [5, 5],
      ],
    },
  },

  // Level 10: Algoritma kompleks - wall follower
  {
    id: 10,
    name: "The Labyrinth",
    description: "Navigasi labirin kompleks! Gunakan semua yang kamu pelajari: loop, sensor, dan logika!",
    gridSize: 8,
    start: [0, 0],
    goal: [7, 7],
    walls: [
      [0, 2],
      [0, 5],
      [1, 2],
      [1, 4],
      [2, 4],
      [2, 6],
      [3, 1],
      [3, 2],
      [3, 6],
      [4, 1],
      [4, 4],
      [4, 6],
      [5, 1],
      [5, 3],
      [6, 3],
      [6, 5],
      [7, 1],
      [7, 5],
    ],
    hint: "# Level 10: Labirin Sejati!\n# Gabungkan semua yang sudah dipelajari:\n# while loop + sensor (can_move) + logika if/elif\n# Strategi 'wall follower': coba kanan > bawah > kiri > atas\n\nwhile get_row() != 7 or get_col() != 7:  # Selama belum di tujuan\n    if can_move_right():    # Coba kanan dulu\n        move_right()\n    elif can_move_down():   # Lalu coba bawah\n        move_down()\n    elif can_move_left():   # Lalu coba kiri\n        move_left()\n    elif can_move_up():     # Terakhir coba atas\n        move_up()\n",
    challenge: {
      description: "Sekarang coba sendiri! Navigasi labirin kompleks terakhir!",
      gridSize: 8,
      start: [0, 0],
      goal: [7, 7],
      walls: [
        [0, 3],
        [1, 1],
        [1, 3],
        [1, 5],
        [2, 1],
        [2, 5],
        [2, 7],
        [3, 3],
        [3, 5],
        [4, 1],
        [4, 2],
        [4, 3],
        [5, 5],
        [5, 6],
        [6, 1],
        [6, 2],
        [6, 3],
        [7, 3],
      ],
    },
  },
];
